development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: delicacy-vue_production

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: delicacy-vue_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: delicacy-vue_production
